name: CI/CD

on:
  push:
    branches:
      - 'main'
jobs:
  docker_build:
    runs-on: blog
    name: Docker Image Build
    steps:
      - uses: actions/checkout@v2
      - name: "Create env file"
        run: |
          echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env
      - name: Build Docker image
        run: |
          docker build -t simple/blog:${{github.ref_name}} .
          docker image prune --filter="dangling=true" --force
  deploy:
    runs-on: blog
    name: Continuous Deployment
    needs: [docker_build]
    steps:
      - name: Deploy using ssh
        run: |
          if [[ "$(docker ps -a -f name=simple-blog | grep -o simple-blog)" == "simple-blog" ]];\
          then echo "container exist"; echo "killing it!";\
          docker rm simple-blog --force;\
          else echo "container not found";\
          fi \
          && \
          docker run -d --name=simple-blog \
          -e WITH_MIGRATION=true \
          --network=genah-network \
          -p 8008:8000 \
          -v /var/storage/blog/public:/var/www/html/storage/app/public \
          -v /var/storage/blog/app:/var/www/html/storage/app \
          --restart always \
          simple/blog:${{github.ref_name}} &&
          docker container prune --force &&
          docker image prune --force
